server:
  port: 9000

instapage:
  url: https://app.instapage.com
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwYXlsb2FkIjp7ImtleSI6IkFVVEg6VG9rZW46MzgzMjI2MTpyakVaZTMvd1lvendsZWEzOi9zZGVyd2FDUFNlMWF2UXFLNXoreHVZdWw4enZFV1N5QytTc0NhUkM2b2M9In0sImV4cCI6MTYxNDA0MjI0MSwic3ViIjoidXNlcjozODMyMjYxIiwibmJmIjoxNjE0MDM1MDQxfQ.LV4Ryrmv7878STBHArBIaUfNMZcxoxhWlrh49x9ZjX8
  getPages: /api/3/customers/4246416/pages?page=1
  getPage: /preview-server/show-page/
  createPage: /api/3/customers/4246416/pages
  getTemplates: /api/3/templates
